spring:    
    datasource:
        url: jdbc:h2:./CAMUNDACCP
        username: MSCCP
        password: MSCCP
        driver:
            class: org.h2.Driver
        enabled: true     
    jpa:
      properties:
         hibernate:
           temp:
             use_jdbc_metadata_defaults: false
             #dialect: org.hibernate.dialect.h2
      hibernate:
         ddl-auto: create
    h2:
        console:
           enabled: true
           path: /h2-console
           
    rabbitmq: 
        host: 127.0.0.1
        port: 5672
        username: guest
        password: guest     
camunda.bpm:
  default-serialization-format: application/json
  id-generator: strong
  admin-user:
    id: nitesh
    password: nkt@123
    firstName: Nitesh
  filter:
    create: All tasks
server:
   port: 8089